defaults:
    -
        scope:
            path: ""
            type: pages
        values:
            layout: default
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post

#url: http://ompl.kavrakilab.org
url: file:///tmp/foo
highlighter: rouge